### ISSUE TITLE
KDTree constructor doesn't use keyword arguments

### ISSUE THREAD

**Issue by c42f** [KristofferC/KDTrees.jl#13]
Using the example in the documentation, I get

``` julia
julia> using KDTrees

julia> data = rand(3,10^3)
3x1000 Array{Float64,2}:
 0.509235  0.255275  0.475453  0.716626   0.307649   …  0.3656     0.537985  0.944464   0.859301  0.526543
 0.317136  0.873023  0.512503  0.0849477  0.0891595     0.409792   0.354199  0.0355318  0.13734   0.188111
 0.458461  0.719676  0.573519  0.272163   0.0206144     0.0387957  0.214672  0.912494   0.830496  0.176133

julia> tree = KDTree(data, leafsize=10, reorder=false)
ERROR: MethodError: `call` has no method matching call(::Type{KDTrees.KDTree{T<:FloatingPoint}}, ::Array{Float64,2})
Closest candidates are:
  KDTrees.KDTree{T<:FloatingPoint}(::Array{T<:FloatingPoint,2}, ::Array{KDTrees.HyperRectangle{T<:FloatingPoint},1}, ::Array{Int64,1}, ::Array{T<:FloatingPoint,1}, ::Array{Int64,1}, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Bool)
  KDTrees.KDTree{T<:FloatingPoint}(::Array{T<:FloatingPoint,2})
  KDTrees.KDTree{T<:FloatingPoint}(::Array{T<:FloatingPoint,2}, ::Int64)
```

If the KDtree constructor is meant to be used with keyword (rather than positional) arguments, you just need to change the `,` after `data` in the constructor declaration to a `;`.  If not, I guess the documentation needs a fix.

This is with a fairly recent (week old) julia-0.4 build.

**Comment by KristofferC** [comment]
Thank you very much. That's embarassing, having the first example in the readme fail :(

It should be fixed now I hope.

**Comment by c42f** [comment]
No worries, thanks for the nice library.  The patch looks good (personally I think keyword arguments are actually a clearer way to go here, but that would unfortunately break backward compatibility).

**Comment by KristofferC** [comment]
You are right about keywords being better. I made the change to use keyword and I believe I fixed it to  be backwards compatible by making the non keyword constructor simply call the keyword constructor.

**Comment by KristofferC** [comment]
When it comes to the query functions I have my suspicions that the overhead when using keyword arguments are unacceptable but I have to benchmark it.

**Comment by c42f** [comment]
Ah right, good idea forwarding the arguments.  Come to think of it, this seems like a good use for the `@deprecate` macro from base:

``` julia
@deprecate  KDTree{T <: FloatingPoint}(data::Matrix{T}, ls::Int, reord::Bool = true)  KDTree(data, leafsize = ls, reorder = reord)
```

**Comment by KristofferC** [comment]
Good idea, done in 61982b41dc6fdeec0af6c743ab9a398e8b0102ac.
